<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EventType extends \App\Entity\EventType implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'allowed_location' => [parent::class, 'allowed_location', null, 16],
        "\0".parent::class."\0".'capacity_type' => [parent::class, 'capacity_type', null, 16],
        "\0".parent::class."\0".'certificate_enabled' => [parent::class, 'certificate_enabled', null, 16],
        "\0".parent::class."\0".'default_max_participants' => [parent::class, 'default_max_participants', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'recording_enabled' => [parent::class, 'recording_enabled', null, 16],
        "\0".parent::class."\0".'requires_payment' => [parent::class, 'requires_payment', null, 16],
        "\0".parent::class."\0".'sort_order' => [parent::class, 'sort_order', null, 16],
        "\0".parent::class."\0".'typical_duration_hours' => [parent::class, 'typical_duration_hours', null, 16],
        "\0".parent::class."\0".'visibility' => [parent::class, 'visibility', null, 16],
        'allowed_location' => [parent::class, 'allowed_location', null, 16],
        'capacity_type' => [parent::class, 'capacity_type', null, 16],
        'certificate_enabled' => [parent::class, 'certificate_enabled', null, 16],
        'default_max_participants' => [parent::class, 'default_max_participants', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'events' => [parent::class, 'events', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'is_active' => [parent::class, 'is_active', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'recording_enabled' => [parent::class, 'recording_enabled', null, 16],
        'requires_payment' => [parent::class, 'requires_payment', null, 16],
        'sort_order' => [parent::class, 'sort_order', null, 16],
        'typical_duration_hours' => [parent::class, 'typical_duration_hours', null, 16],
        'visibility' => [parent::class, 'visibility', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
