<?php

namespace ContainerAYqhCot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8FMl_V3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8FMl.v3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8FMl.v3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'listing' => ['privates', '.errored..service_locator.8FMl.v3.App\\Entity\\Listing', NULL, 'Cannot autowire service ".service_locator.8FMl.v3": it needs an instance of "App\\Entity\\Listing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'listing' => 'App\\Entity\\Listing',
        ]);
    }
}
