<?php

namespace ContainerAYqhCot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OfcWIppService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ofcWIpp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ofcWIpp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artworkRepository' => ['privates', 'App\\Repository\\ArtworkRepository', 'getArtworkRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'artworkRepository' => 'App\\Repository\\ArtworkRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
