<?php

namespace ContainerAYqhCot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Mog82Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Mog8_2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Mog8_2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventType' => ['privates', '.errored..service_locator.4Mog8_2.App\\Entity\\EventType', NULL, 'Cannot autowire service ".service_locator.4Mog8_2": it needs an instance of "App\\Entity\\EventType" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'eventType' => 'App\\Entity\\EventType',
        ]);
    }
}
