<?php

namespace ContainerAYqhCot;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentModerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommentModerationService' shared autowired service.
     *
     * @return \App\Service\CommentModerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommentModerationService.php';

        return $container->privates['App\\Service\\CommentModerationService'] = new \App\Service\CommentModerationService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('OPENAI_API_KEY'), 'https://api.openai.com/v1', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
