<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QF6RKsnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qF6RKsn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qF6RKsn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'artworkRepository' => ['privates', 'App\\Repository\\ArtworkRepository', 'getArtworkRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'artworkRepository' => 'App\\Repository\\ArtworkRepository',
            'em' => '?',
        ]);
    }
}
