<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B45N0kOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b45N0kO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b45N0kO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'communityRepository' => ['privates', 'App\\Repository\\CommunityRepository', 'getCommunityRepositoryService', true],
        ], [
            'communityRepository' => 'App\\Repository\\CommunityRepository',
        ]);
    }
}
