<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAcQlMJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FAcQlMJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FAcQlMJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventType' => ['privates', '.errored..service_locator.FAcQlMJ.App\\Entity\\EventType', NULL, 'Cannot autowire service ".service_locator.FAcQlMJ": it needs an instance of "App\\Entity\\EventType" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eventType' => 'App\\Entity\\EventType',
        ]);
    }
}
