<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtworkApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ArtworkApiController' shared autowired service.
     *
     * @return \App\Controller\ArtworkApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArtworkApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ImageResizer.php';

        $container->services['App\\Controller\\ArtworkApiController'] = $instance = new \App\Controller\ArtworkApiController(($container->privates['App\\Repository\\ArtworkRepository'] ?? $container->load('getArtworkRepositoryService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\ImageResizer());

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\ArtworkApiController', $container));

        return $instance;
    }
}
