<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EventApiController' shared autowired service.
     *
     * @return \App\Controller\EventApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'EventApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EventNotifier.php';

        $a = ($container->privates['App\\Repository\\ParticipantRepository'] ?? $container->load('getParticipantRepositoryService'));

        $container->services['App\\Controller\\EventApiController'] = $instance = new \App\Controller\EventApiController(($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), $a, ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\EventNotifier(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), $a));

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\EventApiController', $container));

        return $instance;
    }
}
