<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FrontOfficeController' shared autowired service.
     *
     * @return \App\Controller\FrontOfficeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FrontOfficeController.php';

        $container->services['App\\Controller\\FrontOfficeController'] = $instance = new \App\Controller\FrontOfficeController(($container->privates['App\\Repository\\ArtworkRepository'] ?? $container->load('getArtworkRepositoryService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\ListingRepository'] ?? $container->load('getListingRepositoryService')), ($container->privates['App\\Repository\\OffreRepository'] ?? $container->load('getOffreRepositoryService')), ($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\PostReactionRepository'] ?? $container->load('getPostReactionRepositoryService')), ($container->privates['App\\Repository\\ParticipantRepository'] ?? $container->load('getParticipantRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\FrontOfficeController', $container));

        return $instance;
    }
}
