<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketplaceApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MarketplaceApiController' shared autowired service.
     *
     * @return \App\Controller\MarketplaceApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MarketplaceApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PaymentService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'InvoiceGenerator.php';

        $container->services['App\\Controller\\MarketplaceApiController'] = $instance = new \App\Controller\MarketplaceApiController(($container->privates['App\\Repository\\ListingRepository'] ?? $container->load('getListingRepositoryService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\PaymentService(), ($container->privates['App\\Service\\InvoiceGenerator'] ??= new \App\Service\InvoiceGenerator()));

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\MarketplaceApiController', $container));

        return $instance;
    }
}
