<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketplaceDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MarketplaceDashboardController' shared autowired service.
     *
     * @return \App\Controller\MarketplaceDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MarketplaceDashboardController.php';

        $container->services['App\\Controller\\MarketplaceDashboardController'] = $instance = new \App\Controller\MarketplaceDashboardController(($container->privates['App\\Repository\\ListingRepository'] ?? $container->load('getListingRepositoryService')), ($container->privates['App\\Repository\\OffreRepository'] ?? $container->load('getOffreRepositoryService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\MarketplaceDashboardController', $container));

        return $instance;
    }
}
