<?php

namespace ContainerJxixxcN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostAdminControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PostAdminController' shared autowired service.
     *
     * @return \App\Controller\PostAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PostAdminController.php';

        $container->services['App\\Controller\\PostAdminController'] = $instance = new \App\Controller\PostAdminController();

        $instance->setContainer(($container->privates['.service_locator.modi9RY'] ?? $container->load('get_ServiceLocator_Modi9RYService'))->withContext('App\\Controller\\PostAdminController', $container));

        return $instance;
    }
}
