<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEmGNn9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEmGNn9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEmGNn9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEmGNn9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXEmGNn9\App_KernelDevDebugContainer([
    'container.build_hash' => 'XEmGNn9',
    'container.build_id' => '51ed6aa5',
    'container.build_time' => 1765672962,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEmGNn9');
