<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxixxcN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxixxcN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxixxcN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxixxcN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxixxcN\App_KernelDevDebugContainer([
    'container.build_hash' => 'JxixxcN',
    'container.build_id' => '8c7ce3b8',
    'container.build_time' => 1765635396,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxixxcN');
